export default [
    {
        nome : 'ASTROGILDO MAGINES SANTYS',
        consultorio : 'A-18',
        especializacao: 'DENTISTA',
        prioridade : 'REGULAR', 
    },
    {
        nome : 'MAGINES SANTYS SILVA',
        consultorio : 'A-19',
        especializacao: 'PEDIATRA',
        prioridade : 'REGULAR', 
    },
    {
        nome : 'SANTYS ASTROGILDO ',
        consultorio : 'A-20',
        especializacao: 'DENTISTA',
        prioridade : 'REGULAR', 
    },
    {
        nome : 'AGNALDO  SANTYS',
        consultorio : 'A-22',
        especializacao: 'DENTISTA',
        prioridade : 'REGULAR', 
    },
    {
        nome : 'AGNALDO  SANTYS',
        consultorio : 'A-22',
        especializacao: 'DENTISTA',
        prioridade : 'REGULAR', 
    },
    {
        nome : 'AGNALDO  SANTYS',
        consultorio : 'A-22',
        especializacao: 'DENTISTA',
        prioridade : 'REGULAR', 
    },
    {
        nome : 'AGNALDO  SANTYS',
        consultorio : 'A-22',
        especializacao: 'DENTISTA',
        prioridade : 'REGULAR', 
    },
    {
        nome : 'AGNALDO  SANTYS',
        consultorio : 'A-22',
        especializacao: 'DENTISTA',
        prioridade : 'REGULAR', 
    },
    {
        nome : 'AGNALDO  SANTYS',
        consultorio : 'A-22',
        especializacao: 'DENTISTA',
        prioridade : 'REGULAR', 
    },
    {
        nome : 'AGNALDO  SANTYS',
        consultorio : 'A-22',
        especializacao: 'DENTISTA',
        prioridade : 'REGULAR', 
    },
    {
        nome : 'AGNALDO  SANTYS',
        consultorio : 'A-22',
        especializacao: 'DENTISTA',
        prioridade : 'REGULAR', 
    },
    {
        nome : 'AGNALDO  SANTYS',
        consultorio : 'A-22',
        especializacao: 'DENTISTA',
        prioridade : 'REGULAR', 
    },
    {
        nome : 'AGNALDO  SANTYS',
        consultorio : 'A-22',
        especializacao: 'DENTISTA',
        prioridade : 'REGULAR', 
    },
    {
        nome : 'AGNALDO  SANTYS',
        consultorio : 'A-22',
        especializacao: 'DENTISTA',
        prioridade : 'REGULAR', 
    },
]