export default [
    {
        nome : 'Astrogildo Magines Santys',
        consultorio : 'A-18',
        especializacao: 'Dentista',
        prioridade : 'Regular', 
    },
    {
        nome : 'Astrogildo Magines Santys',
        consultorio : 'A-18',
        especializacao: 'Dentista',
        prioridade : 'Regular', 
    },
    {
        nome : 'Astrogildo Magines Santys',
        consultorio : 'A-18',
        especializacao: 'Dentista',
        prioridade : 'Regular', 
    },
    {
        nome : 'Astrogildo Magines Santys',
        consultorio : 'A-18',
        especializacao: 'Dentista',
        prioridade : 'Regular', 
    },
    {
        nome : 'Astrogildo Magines Santys',
        consultorio : 'A-18',
        especializacao: 'Dentista',
        prioridade : 'Regular', 
    },
    {
        nome : 'Astrogildo Magines Santys',
        consultorio : 'A-18',
        especializacao: 'Dentista',
        prioridade : 'Regular', 
    },
    {
        nome : 'Astrogildo Magines Santys',
        consultorio : 'A-18',
        especializacao: 'Dentista',
        prioridade : 'Regular', 
    },
    {
        nome : 'Astrogildo Magines Santys',
        consultorio : 'A-18',
        especializacao: 'Dentista',
        prioridade : 'Regular', 
    },
    {
        nome : 'Astrogildo Magines Santys',
        consultorio : 'A-18',
        especializacao: 'Dentista',
        prioridade : 'Regular', 
    },
    {
        nome : 'Astrogildo Magines Santys',
        consultorio : 'A-18',
        especializacao: 'Dentista',
        prioridade : 'Regular', 
    },
    {
        nome : 'Astrogildo Magines Santys',
        consultorio : 'A-18',
        especializacao: 'Dentista',
        prioridade : 'Regular', 
    },
    {
        nome : 'Astrogildo Magines Santys',
        consultorio : 'A-18',
        especializacao: 'Dentista',
        prioridade : 'Regular', 
    },
    {
        nome : 'Astrogildo Magines Santys',
        consultorio : 'A-18',
        especializacao: 'Dentista',
        prioridade : 'Regular', 
    },
    {
        nome : 'Astrogildo Magines Santys',
        consultorio : 'A-18',
        especializacao: 'Dentista',
        prioridade : 'Regular', 
    },
]